#!/bin/bash

#SBATCH --partition=gpu 
#SBATCH --gpus=1
#SBATCH --job-name=30_90
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=18
#SBATCH --time=00:30:00
#SBATCH --output=job_outputs/30_90_%A.out

module purge
module load 2024
module load Anaconda3/2024.06-1
source activate deeprisk_env_2024_3

srun python experiments/biobank_reconstruction.py \
    --config.run_name="30_90"
    --config.freq_mult=(30.0, 90.0)